service: serverless-cicd-aws-nodejs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello

    events:

      - iot:
          sql: "SELECT * FROM 'some_topic'"
